jobs:
  build:
    docker:
      - image: circleci/ubuntu
    steps:
      - checkout
      - run: echo "test"
  test:
    docker:
      - image: circleci/ubuntu
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
