jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running pipeline"
      - run: export gitBranch=$(git branch)
      - run: echo $gitBranch
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
