jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running pipeline"
      - run: echo ${CIRCLE_BRANCH}
      - run: export TF_VAR_custom_branch=${CIRCLE_BRANCH}
      - run: echo $TF_VAR_custom_branch
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
