jobs:
  build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: | 
          terraform -v
      - run: | 
          echo "Running pipeline" &&
          echo ${CIRCLE_BRANCH} &&
          export TF_VAR_custom_branch=${CIRCLE_BRANCH} &&
          echo $TF_VAR_custom_branch &&
          ls &&
          terraform apply
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
